### ISSUE TITLE
assets should use relative paths rather than absolute ones

### ISSUE THREAD

**Issue by tsankuanglee** [ArnoldSmith86/virtualtabletop-library#10]
While working on  #https://github.com/ArnoldSmith86/virtualtabletop/issues/712
I noticed that the asset links, in the json files are absolute ones. For example, in `ejra.json` in `Bulls.vtt`, line 697, we have

```
 "value": "/assets/-607361757_73020"
```

But the leading slash is too restrictive. ​If we remove the leading slash, like this:

```
​"value": "assets/-607361757_73020"
```
then we can have the flexibility of moving the asset directory anywhere.

Doing so does not affect the current code compatibility; it only gives us more flexibility.

I can do a batch update for all files, if folks think it's good doing so

**Comment by rogerl50** [comment]
I think that this issue should be opened in virtualtabletop, not virtualtabletop-library. But I could be wrong.

Further, if you want to do this, then you should open a PR, post proposed change code, so that we can have a discussion about it. That tends to be the way things work here - people look at PRs, not issues, in general, to decide what to change. Not always, but usually.

**Comment by ArnoldSmith86** [comment]
My approach would be to run an nginx server in front of vtt so it can proxy a subdirectory to the vtt server. If you need help setting that up, we can chat on Discord. We should probably write a wiki page for it.

Changing to relative paths might be a good idea but it's not as simple as batch replacing because the public library only contains a fraction of compatible games. It would need a fileupdater in the code so any loaded vtt file will be updated when loaded (we do this for other stuff already). Note that the URLs are used in `css` properties and routines as well.

**Comment by tsankuanglee** [comment]
Thanks, @ArnoldSmith86 . I am indeed using nginx to proxy for several docker containers' services. Having a root path will collide with other project so I prefer keeping everything under its own app's scope.

My PR translates library files on the fly, without actually changing them, for backward compatibility. I need help testing though, to see whether I missed something.

I opened this issue to suggest that we mandate relative paths from now on. It's not code related so I thought this discussion should be in the library repo.

**Comment by ArnoldSmith86** [comment]
This was implemented a while back.
